---
test:
  name: healthcare
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
  - label: create
    description: Create asset dicom
    txNumber: 250
    rateControl:
      type: fixed-rate
      opts:
        tps: 100
    arguments:
      dicom: 10
    callback: benchmarks/scenario/simple/bcshield/create-asset.js
  - label: query
    description: Query dicom asset
    txNumber: 100
    rateControl:
      type: linear-rate
      opts:
        startingTps: 50
        finishingTps: 250
    callback: benchmarks/scenario/simple/bcshield/get-asset.js
#   - label: transfer
#     description: Test description for transfering money between accounts
#     txNumber: 100
#     rateControl:
#           type: fixed-rate
#           opts:
#               tps: 50
#     arguments:
#         money: 100
#     callback: benchmarks/scenario/simple/transfer.js
# monitor:
# ---
# test:
#   workers:
#     type: local
#     number: 1
#   rounds:
#     - label: add asset
#       description: >-
#         Test description for the opening of an account through the deployed
#         chaincode
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 50
#       callback: benchmarks/scenario/simple/bcshield/create-asset.js
#       arguments:
#         txnPerBatch: 100
#     - label: query asset
#       description:  >-
#          Query a asset on blockchain
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 50
#       callback: benchmarks/scenario/simple/bcshield/get-asset.js
  #      module: benchmarks/samples/fabric/fabcar/open-create.js
  # - label: query
  #   description: Test description for the query performance of the deployed chaincode
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 50
  #   callback: benchmarks/scenario/simple/bcshield/query.js
  # - label: transfer
  #   description: Test description for transfering money between accounts
  #   txNumber: 100
  #   rateControl:
  #         type: fixed-rate
  #         opts:
  #             tps: 50
  #   arguments:
  #       money: 100
  #   callback: benchmarks/scenario/simple/transfer.js

monitor:
  type:
  - docker
  docker:  
    containers:
      - peer0.hprovider.healthcare.com
      - peer1.hprovider.healthcare.com
      - peer0.research.healthcare.com
      - peer1.research.healthcare.com
      - peer0.patient.healthcare.com 
      - peer1.patient.healthcare.com 
    charting:
      bar:
        metrics: [Memory(avg), CPU%(avg)]
      polar:
        metrics: [all]

# monitor:
#   type:
#   - docker
#   docker:
#     name:
#     - peer0.hprovider.healthcare.com
#     - peer1.hprovider.healthcare.com
#     - peer0.research.healthcare.com
#     - peer1.research.healthcare.com
#     - peer0.patient.healthcare.com 
#     - peer1.patient.healthcare.com 
#   interval: 5
#   charting:
#   bar:
#     metrics: [Memory(avg), CPU%(avg)]
#   polar:
#     metrics: [all]
# observer:
#     type: local
#     interval: 30