---
test:
  workers:
    type: local
    number: 1
  rounds:
    - label: add asset
      description: >-
        Test description for the opening of an account through the deployed
        chaincode
      txNumber: 100
      rateControl:
        type: fixed-rate
        opts:
          tps: 50
      callback: benchmarks/scenario/simple/bcshield/open.js
      arguments:
        txnPerBatch: 100
  #      module: benchmarks/samples/fabric/fabcar/open-create.js
  # - label: query
  #   description: Test description for the query performance of the deployed chaincode
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 50
  #   callback: benchmarks/scenario/simple/bcshield/query.js
  # - label: transfer
  #   description: Test description for transfering money between accounts
  #   txNumber: 100
  #   rateControl:
  #         type: fixed-rate
  #         opts:
  #             tps: 50
  #   arguments:
  #       money: 100
  #   callback: benchmarks/scenario/simple/transfer.js
monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1