---
test:
  name: healthcare
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
  - label: create
    description: Create asset dicom
    txNumber: 100
    rateControl:
      type: composite-rate
      opts:
        weights:
          - 1
          - 1
          - 1
          - 1
          - 1
        rateControllers:
          - type: fixed-rate
            opts:
              tps: 50
          - type: fixed-rate
            opts:
              tps: 100
          - type: fixed-rate
            opts:
              tps: 150
          - type: fixed-rate
            opts:
              tps: 200
          - type: fixed-rate
            opts:
              tps: 250
        logChange: true
    arguments:
      dicom: 10
    callback: benchmarks/scenario/simple/bcshield/create-asset.js
  - label: query
    description: Query dicom asset
    txNumber: 100
    rateControl:
      type: linear-rate
      opts:
        startingTps: 50
        finishingTps: 250
    callback: benchmarks/scenario/simple/bcshield/get-asset.js
#   - label: transfer
#     description: Test description for transfering money between accounts
#     txNumber: 100
#     rateControl:
#           type: fixed-rate
#           opts:
#               tps: 50
#     arguments:
#         money: 100
#     callback: benchmarks/scenario/simple/transfer.js
# monitor:
# ---
# test:
#   workers:
#     type: local
#     number: 1
#   rounds:
#     - label: add asset
#       description: >-
#         Test description for the opening of an account through the deployed
#         chaincode
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 50
#       callback: benchmarks/scenario/simple/bcshield/create-asset.js
#       arguments:
#         txnPerBatch: 100
#     - label: query asset
#       description:  >-
#          Query a asset on blockchain
#       txNumber: 100
#       rateControl:
#         type: fixed-rate
#         opts:
#           tps: 50
#       callback: benchmarks/scenario/simple/bcshield/get-asset.js
  #      module: benchmarks/samples/fabric/fabcar/open-create.js
  # - label: query
  #   description: Test description for the query performance of the deployed chaincode
  #   txNumber: 1000
  #   rateControl:
  #     type: fixed-rate
  #     opts:
  #       tps: 50
  #   callback: benchmarks/scenario/simple/bcshield/query.js
  # - label: transfer
  #   description: Test description for transfering money between accounts
  #   txNumber: 100
  #   rateControl:
  #         type: fixed-rate
  #         opts:
  #             tps: 50
  #   arguments:
  #       money: 100
  #   callback: benchmarks/scenario/simple/transfer.js
# monitor:
#   type:
#   - docker
#   docker:
#     name:
#     - peer0.hprovider.healthcare.com
#     - peer1.hprovider.healthcare.com
#     - peer0.research.healthcare.com
#     - peer1.research.healthcare.com
#     - peer0.patient.healthcare.com 
#     - peer1.patient.healthcare.com 
#     charting:
#       bar:
#         metrics: [Memory(avg), CPU%(avg)]
#   interval: 5
# observer:
#     type: local
#     interval: 30

monitor:
  type:
    - docker
  docker:
    metrics:
      ignore:
        - prometheus
        - pushGateway
        - cadvisor
        - grafana
        - node-exporter
        - ca.hprovider.healthcare.com
        - ca.research.healthcare.com
        - ca.patient.healthcare.com
      include:
        Avg Memory (MB):
          query: 'sum(container_memory_rss{name=~".+"}) by (name)'
          step: 10
          label: name
          statistic: avg
          multiplier: 0.000001
        CPU (%):
          query: >-
            sum(rate(container_cpu_usage_seconds_total{name=~".+"}[1m])) by
            (name)
          step: 10
          label: name
          statistic: avg
          multiplier: 100
        Network In (MB):
          query: >-
            sum(rate(container_network_receive_bytes_total{name=~".+"}[1m])) by
            (name)
          step: 10
          label: name
          statistic: sum
          multiplier: 0.000001
        Network Out (MB):
          query: >-
            sum(rate(container_network_transmit_bytes_total{name=~".+"}[1m])) by
            (name)
          step: 10
          label: name
          statistic: sum
          multiplier: 0.000001
        Disc Write (MB):
          query: 'sum(rate(container_fs_writes_bytes_total{name=~".+"}[1m])) by (name)'
          step: 10
          label: name
          statistic: sum
          multiplier: 0.000001
        Disc Read (MB):
          query: 'sum(rate(container_fs_reads_bytes_total{name=~".+"}[1m])) by (name)'
          step: 10
          label: name
          statistic: sum
          multiplier: 0.000001
observer:
  type: local
  interval: 10