name: Fabric
version: "1.0"
mutual-tls: false

caliper:
  blockchain: fabric
  # command:
  #   start: export FABRIC_VERSION=1.4.4;export FABRIC_CA_VERSION=1.4.4;docker-compose -f networks/fabric/docker-compose/2hproviderpeercouchdb_solo_raft/docker-compose-tls.yaml up -d;sleep 10s
  #   end: docker-compose -f networks/fabric/docker-compose/2hproviderpeercouchdb_solo_raft/docker-compose-tls.yaml down;(test -z \"$(docker ps -aq)\") || docker rm $(docker ps -aq);(test -z \"$(docker images dev* -q)\") || docker rmi $(docker images dev* -q);rm -rf /tmp/hfc-*

info:
  Version: 2.0.0
  Size: 3 Orgs with 2 Peer
  Orderer: solo
  Distribution: Single Host
  StateDB: CouchDB

clients:
  client0.hprovider.healthcare.com:
    client:
      organization: HProvider
      credentialStore:
        path: /tmp/hfc-kvs/hprovider
        cryptoStore:
          path: /tmp/hfc-cvs/hprovider
      clientPrivateKey:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/users/User1@hprovider.healthcare.com/msp/keystore/721ca1f14efeab0febe4497267dfb631a93109a07bd5b16ad48249d023b7bf35_sk
      clientSignedCert:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/users/User1@hprovider.healthcare.com/msp/signcerts/User1@hprovider.healthcare.com-cert.pem

  client0.research.healthcare.com:
    client:
      organization: Research
      credentialStore:
        path: /tmp/hfc-kvs/research
        cryptoStore:
          path: /tmp/hfc-cvs/research
      clientPrivateKey:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/users/User1@research.healthcare.com/msp/keystore/a770af6ceecc9023d55d5f7827929ef649bae167bd37ad09f76b26a2c5f76d6a_sk
      clientSignedCert:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/users/User1@research.healthcare.com/msp/signcerts/User1@research.healthcare.com-cert.pem

  client0.patient.healthcare.com:
    client:
      organization: Patient
      credentialStore:
        path: /tmp/hfc-kvs/patient
        cryptoStore:
          path: /tmp/hfc-cvs/patient
      clientPrivateKey:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/users/User1@patient.healthcare.com/msp/keystore/3f8efffea44055c1a25d6b59e7e8c0d647ef32a5c3b912cc57f26dac63f9a279_sk
      clientSignedCert:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/users/User1@patient.healthcare.com/msp/signcerts/User1@patient.healthcare.com-cert.pem

channels:
  healthchannel:
    configBinary: networks/fabric/bcshield/channel-artifacts/channel.tx
    created: true
    orderers:
    - orderer.healthcare.com
    peers:
      peer0.hprovider.healthcare.com:
        eventSource: true
      peer0.research.healthcare.com:
        eventSource: true
      peer0.patient.healthcare.com:
        eventSource: true

    chaincodes:
    - id: dicom
      version: "1"
      language: golang
      path: src/fabric/imaging-contract
      #metadataPath: src/fabric/imaging-contract


organizations:
  HProvider:
    mspid: HProviderMSP
    peers:
    - peer0.hprovider.healthcare.com
    - peer1.hprovider.healthcare.com
    certificateAuthorities:
    - ca.hprovider.healthcare.com
    adminPrivateKey:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp/keystore/6540e8fb0b662b3d93ce558da3564784fa1c19538a431b1ff33bf44529b11a7e_sk
    signedCert:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/users/Admin@hprovider.healthcare.com/msp/signcerts/Admin@hprovider.healthcare.com-cert.pem

  Research:
    mspid: ResearchMSP
    peers:
    - peer0.research.healthcare.com
    - peer1.research.healthcare.com
    certificateAuthorities:
    - ca.research.healthcare.com
    adminPrivateKey:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/users/Admin@research.healthcare.com/msp/keystore/575a5240ab760b0e6d8d27411826bd2c16618d8ebbae9a906678da0e87084f7a_sk
    signedCert:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/users/Admin@research.healthcare.com/msp/signcerts/Admin@research.healthcare.com-cert.pem

  Patient:
    mspid: PatientMSP
    peers:
    - peer0.patient.healthcare.com
    - peer1.patient.healthcare.com
    certificateAuthorities:
    - ca.patient.healthcare.com
    adminPrivateKey:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/users/Admin@patient.healthcare.com/msp/keystore/a3bbb7520157d635700176b6d4ad40a68563dcf0b54f11593f64491373f21bbf_sk
    signedCert:
      path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/users/Admin@patient.healthcare.com/msp/signcerts/Admin@patient.healthcare.com-cert.pem

orderers:
  orderer.healthcare.com:
    url: grpcs://localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.healthcare.com
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp/tlscacerts/tlsca.healthcare.com-cert.pem

peers:
  peer0.hprovider.healthcare.com:
    url: grpcs://localhost:7051
    grpcOptions:
      ssl-target-name-override: peer0.hprovider.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/msp/tlscacerts/tlsca.hprovider.healthcare.com-cert.pem

  peer1.hprovider.healthcare.com:
    url: grpcs://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer1.hprovider.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp/tlscacerts/tlsca.hprovider.healthcare.com-cert.pem

  peer0.research.healthcare.com:
    url: grpcs://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.research.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/msp/tlscacerts/tlsca.research.healthcare.com-cert.pem
  peer1.research.healthcare.com:
    url: grpcs://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer1.research.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/msp/tlscacerts/tlsca.research.healthcare.com-cert.pem

  peer0.patient.healthcare.com:
    url: grpcs://localhost:12051
    grpcOptions:
      ssl-target-name-override: peer0.patient.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/peers/peer0.patient.healthcare.com/msp/tlscacerts/tlsca.patient.healthcare.com-cert.pem
  
  peer1.patient.healthcare.com:
    url: grpcs://localhost:13051
    grpcOptions:
      ssl-target-name-override: peer1.patient.healthcare.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/peers/peer1.patient.healthcare.com/msp/tlscacerts/tlsca.patient.healthcare.com-cert.pem


certificateAuthorities:
  ca.hprovider.healthcare.com:
    url: https://localhost:7054
    httpOptions:
      verify: false
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/hprovider.healthcare.com/tlsca/tlsca.hprovider.healthcare.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw

  ca.research.healthcare.com:
    url: https://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/research.healthcare.com/tlsca/tlsca.research.healthcare.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw

  ca.patient.healthcare.com:
    url: https://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
        path: networks/fabric/bcshield/crypto-config/peerOrganizations/patient.healthcare.com/tlsca/tlsca.patient.healthcare.com-cert.pem
    registrar:
    - enrollId: admin
      enrollSecret: adminpw
