# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.healthcare.com:
    container_name: orderer.healthcare.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/:/var/hyperledger/orderer/tls
        - orderer.healthcare.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.hprovider.healthcare.com:
    container_name: peer0.hprovider.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hprovider.healthcare.com
      - CORE_PEER_ADDRESS=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hprovider.healthcare.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hprovider.healthcare.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=HProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hprovider.healthcare.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.hprovider.healthcare.com:
    container_name: peer1.hprovider.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hprovider.healthcare.com
      - CORE_PEER_ADDRESS=peer1.hprovider.healthcare.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hprovider.healthcare.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hprovider.healthcare.com:7051
      - CORE_PEER_LOCALMSPID=HProviderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hprovider.healthcare.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.research.healthcare.com:
    container_name: peer0.research.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.research.healthcare.com
      - CORE_PEER_ADDRESS=peer0.research.healthcare.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.research.healthcare.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.research.healthcare.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.research.healthcare.com:10051
      - CORE_PEER_LOCALMSPID=ResearchMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer0.research.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0.research.healthcare.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.research.healthcare.com:
    container_name: peer1.research.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.research.healthcare.com
      - CORE_PEER_ADDRESS=peer1.research.healthcare.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.research.healthcare.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.research.healthcare.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.research.healthcare.com:9051
      - CORE_PEER_LOCALMSPID=ResearchMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/research.healthcare.com/peers/peer1.research.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.research.healthcare.com:/var/hyperledger/production
    ports:
      - 10051:10051


#---------------------------------- New Peers -------------------------------

  peer0.patient.healthcare.com:
    container_name: peer0.patient.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.patient.healthcare.com
      - CORE_PEER_ADDRESS=peer0.patient.healthcare.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.patient.healthcare.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.healthcare.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.healthcare.com:12051
      - CORE_PEER_LOCALMSPID=PatientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patient.healthcare.com/peers/peer0.patient.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patient.healthcare.com/peers/peer0.patient.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0.patient.healthcare.com:/var/hyperledger/production

    ports:
      - 12051:12051

  peer1.patient.healthcare.com:
    container_name: peer1.patient.healthcare.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.patient.healthcare.com
      - CORE_PEER_ADDRESS=peer1.patient.healthcare.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer1.patient.healthcare.com:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patient.healthcare.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patient.healthcare.com:12051
      - CORE_PEER_LOCALMSPID=PatientMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patient.healthcare.com/peers/peer1.patient.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patient.healthcare.com/peers/peer1.patient.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.patient.healthcare.com:/var/hyperledger/production

    ports:
      - 13051:13051
