version: '3'


networks:
  bcshield_local:


services: 
  
  bcshield_mongo:
    image: mongo
    container_name: bcshield_mongo
    ports: 
     - 27020:27017
    networks:
      - bcshield_local

  # assets_banco:
  #   image: bcshield-assets
  #   container_name: assets_banco
  #   ports: 
  #    - 4000:4000
  #   command: python3 add_assets.py
  #   volumes: 
  #     - ./data/:/home/debian/
  #   networks:
  #     - bcshield_local
  #   depends_on: 
  #     - bcshield_mongo

  bcshield_privacy:
    image: bcshield-privacy
    ports: 
      - 5000:5000
    networks:
      - bcshield_local
    depends_on: 
      - bcshield_mongo

  bcshield_observer:
    image: bcshield-observer
    ports: 
      - 6000:6000
    networks:
      - bcshield_local
    depends_on: 
      bcshield_privacy